project:
  type: book
  preview:
    port: 4201
    browser: false

book:
  title: "Disinfo Dictionary"
  subtitle: "A dictionary of Myths and Truths"
  #description: "This dictionary consolidates and debunks chronic disinformation narratives detected by several fact-checking organisations."
  author: "Fellas & Partners"
  date: "last-modified"
  site-url: http://127.0.0.1:4322
  #site-url: https://disinfodict.pages.dev
  #site-url: https://disinfodict.org
  favicon: /all_common_img/DisinfoDict_logo_1x1_trans_small.png
  downloads: [pdf,epub]
  #https://www.opengraph.xyz/
  open-graph: 
    image: /all_common_img/DisinfoDict_opengraph_1200x627.png
  twitter-card:
    creator: "disinfodict"
    site: "disinfodict"
    image: /all_common_img/DisinfoDict_twittercard_800x418.png
  sidebar: 
    style: "floating"
    collapse-level: 1
    logo: all_common_img/DisinfoDict_logo_1x1_trans.png
    title: "search. read. share."
#  body-header: | 
# ::: {.callout-important title="BREAKING" appearance="default" collapse="false"}
# These are breaking NEWS
# :::
  page-footer:
    background: "grey"
    center:
      - text: "Impressum"
        href: impressum.qmd

  chapters:
  - index.qmd
  - part: "Intro" 
    part-de: "Intro" 
    #part-ua: "Вступ"
    chapters:
    - intro/preface.qmd
    - intro/principles.qmd
    - intro/termstech.qmd
    - intro/ualessons.qmd
    - intro/trueukraine.qmd
    - intro/vatniks.qmd
    - intro/narratives.qmd
  - part: "Example Part"
    part-de: "Beispiel Teil"
    #part-ua: "Приклад частини"
    chapters:
    - examplepart/mychapter.qmd
  appendices:  
    - appendix/about.qmd
    - appendix/recommendations.qmd
    - appendix/references.qmd

callout-appearance: simple
bibliography: 
  - intro/preface.bib
  - intro/termstech.bib
  - intro/trueukraine.bib
  - intro/ualessons.bib
  - examplepart/mychapter.bib
  - appendix/recommendations.bib

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: true
    toc: true
    toc-depth: 3
    toc-expand: 1
    email-obfuscation: javascript
    link-external-icon: false
    link-external-newwindow: false
    license: CC BY-NC-ND
    include-in-header: 
      - file: in_header.html
  pdf:
    latex-auto-mk: true
    latex-tinytex: false
    pdf-engine: xelatex
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
    mainfont: "Segoe UI"
    include-in-header:
      text: |
        \usepackage{alphalph}
        \renewcommand*{\thepart}{%
          \AlphAlph{\value{part}}%
        }
        \usepackage{makeidx}
        \makeindex
        \newcommand{\LatexTableFontSize}{\fontsize{6}{9}\selectfont}
        \newcommand{\LatexReturnFontSize}{\fontsize{12}{14}\selectfont}
#        \renewcommand\thepart{\Alph{part}}
#better in references.qmd
#    include-after-body:
#      text: |
#        \printindex
  epub:
    accessibilitySummary: "This publication conforms to WCAG 2.0 Level AA."
    toc: true
    toc-depth: 3
    number-sections: true

babelquarto:
  languagecodes:
  - name: de
    text: "🇩🇪 Deutsch"
  #- name: ua
  #  text: "🇺🇦 Український"
  - name: en
    text: "🇺🇸 English"
  mainlanguage: 'en'
  languages: ['de']
title-de: Desinfo-Lexikon
#title-ua: Словник-дезінформації
subtitle-de: Ein Lexikon der Mythen und Wahrheiten
#subtitle-ua: Словник міфів і правд
#description-de: Dieses Lexikon konsolidiert und entkräftet chronische Desinformations-Narrative, die von verschiedenen Fact-Checking-Organisationen festgestellt wurden.
#description-ua: Цей словник об'єднує та розвінчує хронічні дезінформаційні наративи, виявлені кількома фактчекінговими організаціями
author-de: Fellas & Partner
#author-ua: НАФО & Партнер
lang: en

