# Willkommen {.unnumbered}

> Eine feine Linie trennt in der Vergangenheit die Lüge von der Wahrheit, aber in der Zukunft gibt es keine Linie mehr.  
> — Lesja Ukrainka, Cassandra (1907)

Das **Desinfo-Lexikon** ist eine gut organisierte, durchsuchbare und verlinkbare Online-Ressource, die chronische russische Narrative mit ausgewählten Fakten über Russlands Krieg gegen die Ukraine widerlegt. Desinfo-Lexikon richtet sich an verschiedene Zielgruppen: Es ist eine **Zeitersparnis für Journalisten, Faktenchecker, Desinformationsaktivisten, Nutzer sozialer Netzwerke und alle Bürger, die zuverlässige Informationen über Russland und die Ukraine suchen**. Desinfo-Lexikon ist sowohl ein Web-Lexikon zum Suchen und Nachschlagen als auch ein strukturiertes Buch, das von Anfang bis Ende gelesen werden kann. Es kann online gelesen werden, auf dem Smartphone, oder als pdf oder epub heruntergeladen werden; mit einem Screenreader dient das epub als Hörbuch. Desinfo-Lexikon ist zweisprachig (deutsch/englisch), kostenlos, quelloffen und erweiterbar und füllt eine Lücke zwischen der riesigen [EUvsDisinfo-Datenbank](https://euvsdisinfo.eu/disinformation-cases/) des diplomatischen Dienstes der EU und Wikipedia. 

Wir hoffen dass Desinfo-Lexikon dazu beiträgt, die grassierende Propaganda Russlands zu seinem Krieg in der Ukraine zu reduzieren, und damit zu einer resilienteren Gesellschaft und zur Sicherheit in Europa beizutragen. **read. share. join.**

::: {.content-visible when-format="latex"}
Das Desinfo-Lexikon © 2024 von Fellas & Partnern ist lizensiert unter CC BY-NC-ND 4.0. Für die vollständige Lizenz siehe [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

::: {.content-visible when-format="html"}
Zum barrierefreien Lesen und Hören empfehlen wir die e-book 'epub' downloads in den Sprachen [Deutsch]({{<meta book.site-url>}}/de/Desinfo-Lexikon.epub) und [Englisch]({{<meta book.site-url>}}/Disinfo-Dictionary.epub).

Diese Webseite ist mehrsprachig: Um die Sprache zu wechseln, klicken Sie auf das Globus-Icon 🌐 oben links. Diese Seite hat mehrere Formate: Sie können sie online lesen oder als pdf, epub oder docx herunterladen, indem Sie auf das Download-Icon ⤓ oben links klicken. Die Teil- und Kapitelnavigation befindet sich auf der linken Seite, die Abschnittsnavigation auf der rechten Seite. Um die Abschnittsnavigation auf dem Smartphone sichtbar zu machen, verwenden Sie das Smartphone einfach im Querformat. Um mit dem Lesen zu beginnen, klicken Sie auf „Vorwort“ rechts in der unteren Navigation.

Das Desinfo-Lexikon © 2024 von Fellas & Partnern ist lizensiert unter CC BY-NC-ND 4.0. Für die vollständige Lizenz siehe [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::
