# Ласкаво {.unnumbered}

Ласкаво просимо до словника дезінформації!

У цьому словнику зібрані та розвінчані хронічні дезінформаційні наративи, виявлені кількома фактчекінговими організаціями.

Щоб зробити навігацію сторінками видимою на смартфоні, просто використовуйте його в альбомній орієнтації. Щоб почати читання, натисніть на «Передмова» внизу праворуч або скористайтеся головним меню вгорі ліворуч.

::: {.content-visible when-format="latex"}
Словник дезінформації © 2024 by Fellas \& Partners поширюється за ліцензією CC BY-NC-ND 4.0. Щоб переглянути копію цієї ліцензії, відвідайте [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

::: {.content-visible when-format="html"}
Для безбар'єрного читання та прослуховування рекомендуємо завантажити електронну книгу в форматі «epub» мовами [німецька]({{<meta book.site-url>}}/en/Disinfo-Dictionary.epub) та [англійська]({{<meta book.site-url>}}/Disinfo-Dictionary.epub).

Цей сайт багатомовний: для перемикання мови натисніть на іконку глобуса вгорі ліворуч. Ця сторінка мультиформатна: ви можете читати онлайн або завантажити pdf чи epub, натиснувши на іконку завантаження вгорі ліворуч. Навігація по частинах і главах знаходиться ліворуч, а по розділах - праворуч. Щоб зробити навігацію по розділах видимою на смартфоні, просто використовуйте його в альбомній орієнтації. Щоб почати читати, натисніть на «Передмову» в нижній частині навігації.

Словник дезінформації © 2024 by Fellas \& Partners поширюється за ліцензією CC BY-NC-ND 4.0. Щоб переглянути копію цієї ліцензії, відвідайте  [creativecommons.org](https://creativecommons.org/licenses/by-nc-nd/4.0/)
:::

