---
abstract: > 
  What you didn't know: Find out more about Ukraine, about the origins of Europe and about Russian lies
---

# Learning Ukraine {.unnumbered #sec-intro-trueukraine}

## Worth knowing about Ukraine

The [Kyiv Independent](https://kyivindependent.com) is Ukraine’s fastest-growing English-language media outlet, created in November 2021, just three months before the full-scale Russian invasion of Ukraine. Kyiv Independent has two sections dedicated to Ukraine:

- [Dare to Ukraine](https://kyivindependent.com/dare-to-ukraine/) features a series of videos on Ukrainian towns and regions
- [Explaining Ukraine](https://kyivindependent.com/tag/explaining-ukraine/) features a series of articles that explain Ukrainian historical and cultural events and figures in order to help the world understand Ukraine better

The website [Ukraїner](https://www.ukrainer.net/en/) provides lots of movies, fotos and stories about Ukraine. 

The website [Being Ukraine](https://beingukraine.org/) provides stories and artworks from a nation under fire, made of hope, pride, and resilience.

The free online-book *Being Ukraine* edited by @Lanoux:2024 of the Conneticut College introduces into history and culture of Ukraine. 

The Katapult publishing house distributes a very descriptive book with facts in [100 Maps of Ukraine](https://katapult-verlag.de/programm/100-maps-about-ukraine), here is a [reading sample](https://katapult-verlag.de/media/pages/programm/100-maps-about-ukraine/f96cd1e954-1680001508/100_maps_about_ukraine_english_extract.pdf) and here a [free Russian version](https://www.katapult-shop.de/media/1a/0b/98/1692016540/100-Karten-uber-die-Ukraine_russisch.pdf).

The Q&A website [uaqa.com](https://uaqa.com.ua/en/) allows to ask questions about Ukraine related topics and provides collected answers.

PEN Ukraine has compiled a list of [100 Books to Help Understand Ukraine](https://pen.org.ua/en/100-knyzhok-yaki-dopomozhut-zrozumity-ukrayinu)


## Lies from russia

The newspaper Kyiv Post has published [25 myths and facts about Ukraine and Ukrainians](https://archive.kyivpost.com/article/guide/ukraine-politics/25-myths-and-facts-about-ukraine-and-ukrainians-421341.html). This is a nice list, unfortunately it follows the naive debunking approach of using 25 lies as highlighted section headers (=summaries) of the paragraphs that follow. Very likely readers recall these summaries (=lies). 

Better debunking does [Suspilne Kultura](https://en.wikipedia.org/wiki/Suspilne_Kultura), a Ukrainian public TV channel showcasing culture in Ukraine. It has created a video series on [big russian lies](https://www.youtube.com/@SuspilneKultura/search?query=BIG%20RUSSIAN%20LIES). At the time of writing, the following episodes were available:

- [How Russia REWRITES history in its favor](https://youtu.be/x4_ZsqmkuK4?feature=shared)
- [Russian literature is FAKE!? How the Kremlin uses it for war](https://youtu.be/lyCypK6yOl0?feature=shared)
- [How the Kremlin pushes its «Russian world» using cinema](https://youtu.be/KZTwhjCzgs8?feature=shared)
- [«Swan Lake» on the ruins: how does Russia loot art?](https://youtu.be/Ts_aW9zIiBY?feature=shared)
- [How does the Kremlin LIMITS the media?](https://youtu.be/8YI8FGBf_Yc?feature=shared)
- [“Neutral” athletes are ‘in the grip of pogroms’? How Russia is returning to sports (not yet in English)](https://youtu.be/Na4hu0olADg?feature=shared)

If you want proof for the most evil russian propaganda, see the [articles of Julia Davies](http://www.juliadavisnews.com/articles/) and her [Russian Media Monitor on youtube](https://www.youtube.com/@russianmediamonitor).
