---
abstract: > 
  Was Sie nicht wussten: Erfahren Sie mehr über die Ukraine, den Ursprung Europas und über russische Lügen
---

# Ukraine kennenlernen {.unnumbered #sec-intro-trueukraine}

## Wissenwertes über die Ukraine

The [Kyiv Independent](https://kyivindependent.com) ist das am schnellsten wachsende englischsprachige Medienportal in der Ukraine. Es wurde im November 2021 gegründet, nur drei Monate vor der russischen Invasion in der Ukraine. Kyiv Independent hat zwei Rubriken, die der Ukraine gewidmet sind:

- [Dare to Ukraine](https://kyivindependent.com/dare-to-ukraine/) bietet eine Reihe von Videos über ukrainische Städte und Regionen
- Explaining Ukraine](https://kyivindependent.com/tag/explaining-ukraine/) bietet eine Reihe von Artikeln, die ukrainische historische und kulturelle Ereignisse und Persönlichkeiten erklären, um der Welt zu helfen, die Ukraine besser zu verstehen

Die Website [Ukraїner](https://www.ukrainer.net/de/) bietet viele Filme, Fotos und Geschichten über die Ukraine. 

Die Website [Being Ukraine](https://beingukraine.org/) bietet Geschichten und Kunstwerke aus einem Land, das unter Beschuss steht, das aber auch Hoffnung, Stolz und Widerstandskraft besitzt.

Das kostenlose Online-Buch *Being Ukraine*, herausgegeben von @Lanoux:2024 vom Conneticut College, führt in die Geschichte und Kultur der Ukraine ein. 

Der Katapult Verlag vertreibt ein sehr anschauliche Buch mit Fakten in [100 Karten über die Ukraine](https://katapult-verlag.de/programm/9783948923419-100-karten-uber-die-ukraine), hier ist eine [Leseprobe](https://katapult-verlag.de/media/pages/programm/9783948923419-100-karten-uber-die-ukraine/9767b5d708-1680001390/100-karten-uber-die-ukraine_leseprobe.pdf) und hier eine [kostenlose russische Version](https://www.katapult-shop.de/media/1a/0b/98/1692016540/100-Karten-uber-die-Ukraine_russisch.pdf).

Die Q&A-Website [uaqa.com] (https://uaqa.com.ua/en/) ermöglicht es, Fragen zu ukrainischen Themen zu stellen und sammelt die Antworten.

Das Kinderlexikon [Klexikon](https://klexikon.zum.de) hat sorgfältig geschriebene Artikel zur [Ukraine](https://klexikon.zum.de/wiki/Ukraine) und zum [Russischen Überfall auf die Ukraine](https://klexikon.zum.de/wiki/Russischer_%C3%9Cberfall_auf_die_Ukraine), in anderen Teilen des Klexikon finden sich allerdings auch russiche Narrative.

PEN Ukraine hat eine Liste von [100 Büchern, die helfen, die Ukraine zu verstehen](https://pen.org.ua/en/100-knyzhok-yaki-dopomozhut-zrozumity-ukrayinu) zusammengestellt.


## Lügen aus Russland

Das ausgezeichnete Buch "Ukraine im Fokus" (@Pryhornytska:2023) widerlegt wissenschaftlich in 17 Kapiteln viele der Propagandalügen welche von Russland über die Ukraine in Umlauf gebracht worden sind.

Die Zeitung Kyiv Post hat [25 Mythen und Fakten über die Ukraine und die Ukrainer] veröffentlicht (https://archive.kyivpost.com/article/guide/ukraine-politics/25-myths-and-facts-about-ukraine-and-ukrainians-421341.html). Dies ist eine schöne Liste, leider folgt sie dem naiven Entlarvungsansatz, 25 Lügen als hervorgehobene Abschnittsüberschriften (=Zusammenfassungen) der folgenden Absätze zu verwenden. Sehr wahrscheinlich erinnern sich die Leser an diese Zusammenfassungen (=Lügen). 

Besser macht es [Suspilne Kultura](https://en.wikipedia.org/wiki/Suspilne_Kultura), ein öffentlicher ukrainischer Fernsehsender, der die Kultur in der Ukraine präsentiert. Er hat eine Videoserie über [große russische Lügen](https://www.youtube.com/@SuspilneKultura/search?query=BIG%20RUSSIAN%20LIES) erstellt. Zum Zeitpunkt der Erstellung dieses Artikels waren die folgenden ins Englische übersetzte Episoden verfügbar:

- [Wie Russland die Geschichte zu seinen Gunsten UMSCHREIBT](https://youtu.be/x4_ZsqmkuK4?feature=shared)
- [Russische Literatur ist FAKE!? Wie der Kreml sie für den Krieg nutzt](https://youtu.be/lyCypK6yOl0?feature=shared)
- [Wie der Kreml seine „russische Welt“ mit Hilfe des Kinos vorantreibt](https://youtu.be/KZTwhjCzgs8?feature=shared)
- [„Schwanensee“ auf den Ruinen: Wie plündert Russland die Kunst?](https://youtu.be/Ts_aW9zIiBY?feature=shared)
- [Wie schränkt der Kreml die Medien ein?](https://youtu.be/8YI8FGBf_Yc?feature=shared)
- [„Neutrale“ Athleten sind „in der Gewalt von Pogromen“? Wie Russland zum Sport zurückkehrt (noch nicht auf Englisch)](https://youtu.be/Na4hu0olADg?feature=shared)

Wenn Sie einen Beweis für die übelste russische Propaganda suchen, sehen Sie sich die [Artikel von Julia Davies](http://www.juliadavisnews.com/articles/) und ihren [Russian Media Monitor auf youtube](https://www.youtube.com/@russianmediamonitor) an.
