# Empfehlungen {.unnumbered #sec-appendix-recommendations}

## Andere Lexika

- Sehr zu empfehlen ist das in kleinen Häppchen gut lesbare Lexikon für Putin-Versteher (@Urban:2023) sowie vom selben Autor die Aufarbeitung "VERSTELLTER BLICK: Die deutsche Ostpolitik" (@Urban:2022). 
- Das [Desinformations-Glossar](https://www.disinfo.eu/publications/disinformation-glossary-150-terms-to-understand-the-information-disorder/) des [EU Disinfo Lab](https://www.disinfo.eu)
- Das [Lügenlexikon](https://datasociety.net/library/lexicon-of-lies/) der [Data&Society](https://datasociety.net/)
- Claire Wardles [Information Disorder Glossary](https://journalistsresource.org/politics-and-government/information-disorder-glossary-fake-news/)


## Lehrmaterialien

- Leitlinien für Lehrkräfte und pädagogische Fachkräfte zur Bekämpfung von Desinformation und zur Förderung der digitalen Kompetenz durch allgemeine und berufliche Bildung (@ECDE:2022:de)
- Desinformation entlarven und bekämpfen : Toolkit für Lehrkräfte (@ECDC:2024:de)
- Das Projekt [Framing](https://www.teachtoday.de/Themen/Digitale_Gesellschaft/Desinformation/3795_Projektidee_Framing.htm) ist eines der Projekte von [teachtoday](https://www.teachtoday.de/) von der Telekom zur Entwicklung von Medienkompetenz, weiterhin gibt es eine [Toolbox](https://www.teachtoday.de/2920_Toolbox.htm) und das Medienmagazin [Scroller](https://www.scroller.de/Dein_Magazin/3784_Fakt_oder_Fake.htm) für Kinder und Jugendliche.
- Die Seite [Medienkompetenz stärken](https://www.bmfsfj.de/bmfsfj/themen/kinder-und-jugend/medienkompetenz/medienkompetenz-staerken-75350) des Bundesfamilienministeriums
- Lehrmaterialien der EU für [Schüler bis zu 9 Jahren](https://learning-corner.learning.europa.eu/learning-materials/tackling-disinformation-and-promoting-digital-literacy_de) und für [Schüler von 15 Jahren und älter](https://learning-corner.learning.europa.eu/learning-materials/how-spot-and-fight-disinformation_de)   

## NGOs
- [fellas4europe](https://fellas4europe.org/)
- [EUvsDisinfo](https://euvsdisinfo.eu/ukraine/)
- [StopFake](https://www.stopfake.org/de)
- [MIMIKAMA - zuerst denken - dann klicken](https://www.mimikama.org/)
- [Mediendienst Integration](https://mediendienst-integration.de/) ist eine Informations-Plattform des "Rats für Migration e.V." zu den Themen Flucht, Migration und Diskriminierung, allerdings will der Mediendienst nur Rechts-Extremismus kennen, nicht aber Links-Extremismus oder Probleme mit russischer Unterwanderung deutscher Institutionen.

## Medien

- [European Digital Media Observatory](https://edmo.eu/)
- [dpa Faktencheck](https://www.dpa.com/de/faktencheck)
- [DW (Deutsche Welle)](https://www.dw.com/de/faktencheck/t-56578552)
- [ARD Faktencheck](https://www.tagesschau.de/faktenfinder)
- [ZDF investigativ](https://www.zdf.de/nachrichten/thema/zdf-investigativ-100.html)
- [Correctiv Faktencheck](https://correctiv.org/faktencheck/)
- [Arte Fake news](https://www.arte.tv/de/videos/RC-022858/fake-news/) und [Aktuelles und Gesellschaft](https://www.arte.tv/de/videos/aktuelles-und-gesellschaft/)
- [BBC reality check](https://www.bbc.com/news/reality_check)
- [BBC information disorder](https://www.bbc.co.uk/mediaaction/our-work/information-disorder)
- [CNN facts first](https://edition.cnn.com/politics/fact-check)


## Ukraine War Archive (UWA)

Das [Ukraine War Archive (UWA)](https://ukrainewararchive.org/eng/) ist eine gemeinnützige, gemeinschaftliche Plattform zur digitalen Bewahrung, die ein einheitliches Register von Materialien im Zusammenhang mit der russischen Invasion in der Ukraine erstellt. Mit innovativen technologischen und methodischen Ansätzen dient es ukrainischen und internationalen Organisationen als Instrument zur Bewahrung der Geschichte und zur fairen Darstellung der Ereignisse im rechtlichen, historischen und kulturellen Diskurs, um eine Grundlage für Wahrheit und Gerechtigkeit zu schaffen. Das Ukrainische Kriegsarchiv ist keine öffentliche Ressource. Der Zugang kann nach einer Hintergrundprüfung und Genehmigung gewährt werden. Einige der [Projekte](https://ukrainewararchive.org/eng/projects/) des UWA sind jedoch ganz oder teilweise öffentlich zugänglich. 


## Russischer Medienmonitor

Russische Medien und das russische Fernsehen veröffentlichen jeden Tag Aufrufe zur Vernichtung des ukrainischen Militärs, der ukrainischen Kultur und des ukrainischen Volkes. Eine ausgezeichnete Quelle hierfür ist der *Russian Media Monitor* von Julia Davis - Investigative Reporterin, russische Medienanalystin und Kommentatorin unter [www.russialies.com](http://www.russialies.com).

## Bund

- [FAQ Desinformation im Kontext des russischen Angriffskrieges gegen die Ukraine, Bundesministerioum des Inneren und für Heimat](https://www.bmi.bund.de/SharedDocs/faqs/DE/themen/heimat/desinformation/faq-liste-desinformation.html)  <!-- [](https://www.demokratie-leben.de) -->
- [Bundeszentrale für politische Bildung](https://www.bpb.de/themen/medien-journalismus/digitale-desinformation/)


## [Zentrum Liberale Moderne](https://libmod.de/)

- [NARRATIV-CHECK](https://libmod.de/narrativcheck/)
- [Gegenmedien als Radikalisierungsmaschine](https://gegenmedien.info/)
- [gegner analyse](https://gegneranalyse.de/)

## ÖRR

- [ARD Faktenfinder](https://www.tagesschau.de/faktenfinder)
- [BR Faktenfuchs](https://www.br.de/nachrichten/faktenfuchs-faktencheck,QzSIzl3)
- [ZDF investigativ](https://www.zdf.de/nachrichten/thema/zdf-investigativ-100.html)


## Bücher

- [LEXIKON FÜR PUTIN-VERSTEHER](https://www.edition-fototapeta-shop.de/p/lexikon-fuer-putin-versteher)
- [Putins Netz](https://de.wikipedia.org/wiki/Putins_Netz)
- [Die Moskau-Connection](https://de.wikipedia.org/wiki/Die_Moskau-Connection)


## Experten

Der Desinformationsanalyst Dietmar Pichler baut ein [Disinformation Resilience Network (DRN)](https://www.disinforesilience.eu) auf, eine gemeinnützige und überparteiliche Organisation, die sich der Analyse der Auswirkungen von Desinformation, Propaganda und extremistischen Ideologien durch ausländische und inländische Akteure auf den Informationsraum demokratischer Gesellschaften widmet.

DRN bietet eine Plattform für Experten aus verschiedenen Bereichen wie Politikwissenschaft, Journalismus, Geschichte, Sicherheit und Diplomatie, um Ideen auszutauschen, zusammenzuarbeiten und sich zu vernetzen. DRN arbeitet eng mit nationalen und internationalen Organisationen, Pädagogen, Analysten und Interessenvertretern zusammen, die für diese Themen relevant sind.

Am 29. November 2024 trafen sich unter dem Titel [Foreign Interference, Subversion & Disinformation](https://www.disinforesilience.eu/2024/12/09/foreign-interference-and-disinformation-conference-in-vienna-analyzes-the-local-and-international-situation/) Experten, Diplomaten und Vertreter aus Politik und Zivilgesellschaft zu einem Meinungsaustausch.


