# Recommendations {.unnumbered #sec-appendix-recommendations}

## Other dictionaries

- The [Disinformation Glossary](https://www.disinfo.eu/publications/disinformation-glossary-150-terms-to-understand-the-information-disorder/) of the [EU Disinfo Lab](https://www.disinfo.eu)
- The [Lexicon of Lies](https://datasociety.net/library/lexicon-of-lies/) of [Data&Society](https://datasociety.net/)
- Claire Wardle's [Information Disorder Glossary](https://journalistsresource.org/politics-and-government/information-disorder-glossary-fake-news/)


## Teaching materials

- Guidelines for teachers and educators on tackling disinformation and promoting digital literacy through education and training (@ECDE:2022:en)
- How to spot and fight disinformation - Toolkit for teachers (@ECDC:2024:en)
- EU teaching materials for [pupils aged 9 and under](https://learning-corner.learning.europa.eu/learning-materials/tackling-disinformation-and-promoting-digital-literacy_en) and for [pupils aged 15 and over](https://learning-corner.learning.europa.eu/learning-materials/how-spot-and-fight-disinformation_en)   

## NGOs

- [fellas4europe](https://fellas4europe.org/)
- [EUvsDisinfo](https://euvsdisinfo.eu/ukraine/)
- [StopFake](https://www.stopfake.org/en)
- [MIMIKAMA - think first - then click](https://www.mimikama.org/en/)
- [OPORA](https://oporaua.org/en/category/viyna/antipropaganda/)
- [VoxCheck](https://voxukraine.org/en/)
- [Mediendienst Integration](https://mediendienst-integration.de/en/english/facts-figures.html) is an information platform of the german “Council for Migration e.V.” on the topics of flight, migration and discrimination, and provides some pages in English. However, be aware that they pretend to know only about right-wing extremism, not about left-wing extremism or problems with Russian infiltration of German institutions.

## Media

- [European Digital Media Observatory](https://edmo.eu/)
- [dpa fact checking](https://www.dpa.com/en/fact-checking-at-dpa)
- [DW (Deutsche Welle)](https://www.dw.com/en/fact-check/t-56584214)
- [BBC reality check](https://www.bbc.com/news/reality_check)
- [BBC information disorder](https://www.bbc.co.uk/mediaaction/our-work/information-disorder)
- [CNN facts first](https://edition.cnn.com/politics/fact-check)
- [Arte politics an society](https://www.arte.tv/en/videos/politics-and-society/)


## Ukraine War Archive (UWA)

The [Ukraine War Archive (UWA)](https://ukrainewararchive.org/eng/) is a non-profit collaborative digital preservation platform that creates a unified register of materials related to the Russian full-scale invasion of Ukraine. With innovative technological and methodological approaches, it serves as a tool for Ukrainian and international organizations to preserve history and fairly represent events in legal, historical, and cultural discourse, establishing a foundation for truth and justice. Ukraine War Archive is not a public resource. Access to it can be obtained after a background check and authorisation. However, some of UWA's [projects](https://ukrainewararchive.org/eng/projects/) are publicly accessible in whole or in part. 


## Russian Media Monitor

Russian Media and TV publish every day calls to annihilate the Ukrainian military, Ukrainian culture and the Ukrainian people. An excellent source for this is the *Russian Media Monitor* by Julia Davis – Investigative Reporter, Russian Media Analyst and Commentator at [www.russialies.com](http://www.russialies.com).


## German Government

- [Disinformation related to the Russian war of aggression against Ukraine](https://www.bmi.bund.de/SharedDocs/schwerpunkte/EN/disinformation/disinformation-related-to-the-russian-war-of-aggression-against-ukraine.html)
- [Federal Agency for Civic Education](https://www.bpb.de/die-bpb/ueber-uns/federal-agency-for-civic-education/)

[Center for Liberal Modernity](https://libmod.de/en/)


## Books

[Putin's People: How the KGB Took Back Russia and Then Took On the West](https://en.wikipedia.org/wiki/Putin%27s_People:_How_the_KGB_Took_Back_Russia_and_Then_Took_On_the_West)


## Experts

Disinformation Analyst Dietmar Pichler is building a [Disinformation Resilience Network (DRN)](https://www.disinforesilience.eu), a non-profit and non-partisan organization dedicated to analyzing the impact of disinformation, propaganda, and extremist ideologies by foreign and domestic actors on the information space of democratic societies.

DRN provides a platform for experts from various fields such as political science, journalism, history, security, and diplomacy to exchange ideas, collaborate, and network. DRN works closely with national and international organizations, educators, analysts, and stakeholders relevant to these topics.

On 2024 November 29, under the title [Foreign Interference, Subversion & Disinformation](https://www.disinforesilience.eu/2024/12/09/foreign-interference-and-disinformation-conference-in-vienna-analyzes-the-local-and-international-situation/) experts, diplomats, and representatives from politics and civil society gathered for an exchange of views.


